package com.mrfox.gym;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.view.*;import android.widget.*;import android.text.InputType;import org.json.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int accent=Color.rgb(108,172,227), text=Color.rgb(27,27,27); LinearLayout root,content; ArrayList<Client> clients=new ArrayList<>(); SharedPreferences sp; int photoClient=-1; final int PICK=7; SimpleDateFormat fmt=new SimpleDateFormat("yyyy-MM-dd",Locale.US);
 static class Client{String name,phone,photo="";ArrayList<Pay> pays=new ArrayList<>();}
 static class Pay{String date;double amount;boolean paid;}
 public void onCreate(Bundle b){super.onCreate(b);sp=getSharedPreferences("mrfox",0);load(); if(sp.getString("pin","").isEmpty()) pinSetup(); else pinLogin();}
 TextView tv(String s,int sz,int style){TextView v=new TextView(this);v.setText(s);v.setTextSize(sz);v.setTextColor(text);v.setPadding(18,12,18,12);v.setTypeface(null,style);return v;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(accent);return b;}
 EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine();e.setTextColor(text);return e;}
 void frame(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(Color.WHITE);setContentView(root); LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);bar.setBackgroundColor(accent);String[] tabs={"Clientes","Pagos","Dashboard","Pendientes","Alertas"};for(String t:tabs){TextView x=tv(t,13,1);x.setTextColor(Color.WHITE);x.setOnClickListener(v->show(t));bar.addView(x,new LinearLayout.LayoutParams(0,-2,1));}content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(bar);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));show("Dashboard");}
 void splash(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setGravity(Gravity.CENTER);l.setBackgroundColor(Color.WHITE);ImageView img=new ImageView(this);img.setImageResource(getResources().getIdentifier("ic_fox","drawable",getPackageName()));l.addView(img,new LinearLayout.LayoutParams(320,320));TextView name=tv("Mr Fox",34,1);name.setTextColor(accent);l.addView(name);setContentView(l);} 
 void pinSetup(){splash();new Handler().postDelayed(()->{EditText p=input("Crea PIN de administrador");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);new AlertDialog.Builder(this).setTitle("Mr Fox").setView(p).setPositiveButton("Guardar",(d,w)->{sp.edit().putString("pin",p.getText().toString()).apply();frame();}).setCancelable(false).show();},900);} 
 void pinLogin(){splash();new Handler().postDelayed(()->askPin(),900);} 
 void askPin(){EditText p=input("PIN");p.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);AlertDialog d=new AlertDialog.Builder(this).setTitle("Autenticación por PIN").setView(p).setPositiveButton("Entrar",null).setCancelable(false).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{if(p.getText().toString().equals(sp.getString("pin",""))){d.dismiss();frame();}else Toast.makeText(this,"PIN incorrecto",0).show();}));d.show();}
 void show(String tab){content.removeAllViews(); if(tab.equals("Clientes"))clients(); else if(tab.equals("Pagos"))payments(); else if(tab.equals("Dashboard"))dash(); else if(tab.equals("Pendientes"))pending(); else alerts();}
 void clients(){Button add=btn("+ Nuevo cliente");add.setOnClickListener(v->clientDialog(-1));content.addView(add);for(int i=0;i<clients.size();i++){Client c=clients.get(i);LinearLayout r=new LinearLayout(this);r.setPadding(8,8,8,8);r.setGravity(Gravity.CENTER_VERTICAL);ImageView im=new ImageView(this); if(!c.photo.isEmpty())im.setImageURI(Uri.parse(c.photo));else im.setImageResource(getResources().getIdentifier("ic_fox","drawable",getPackageName()));r.addView(im,new LinearLayout.LayoutParams(100,100));TextView info=tv(c.name+"\n"+c.phone,16,0);r.addView(info,new LinearLayout.LayoutParams(0,-2,1));int ix=i;Button e=btn("Editar");e.setOnClickListener(v->clientDialog(ix));Button del=btn("Eliminar");del.setOnClickListener(v->{clients.remove(ix);save();clients();});r.addView(e);r.addView(del);content.addView(r);}}
 void clientDialog(int ix){Client c=ix>=0?clients.get(ix):new Client();LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);EditText n=input("Nombre"),p=input("Teléfono");n.setText(c.name);p.setText(c.phone);Button photo=btn("Subir/editar foto desde archivos");photo.setOnClickListener(v->{photoClient=ix;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),PICK);});l.addView(n);l.addView(p);l.addView(photo);new AlertDialog.Builder(this).setTitle(ix>=0?"Editar cliente":"Nuevo cliente").setView(l).setPositiveButton("Guardar",(d,w)->{c.name=n.getText().toString();c.phone=p.getText().toString();if(ix<0)clients.add(c);save();clients();}).show();}
 public void onActivityResult(int r,int c,Intent data){super.onActivityResult(r,c,data);if(r==PICK&&data!=null){Uri u=data.getData();getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);if(photoClient>=0)clients.get(photoClient).photo=u.toString();save();show("Clientes");}}
 void payments(){Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_item,names());s.setAdapter(a);content.addView(s);EditText amt=input("Monto"),date=input("Vence / fecha yyyy-MM-dd");date.setText(fmt.format(new Date()));Button add=btn("Registrar pago pendiente");content.addView(amt);content.addView(date);content.addView(add);add.setOnClickListener(v->{if(clients.isEmpty())return;Pay p=new Pay();p.amount=Double.parseDouble(amt.getText().toString());p.date=date.getText().toString();clients.get(s.getSelectedItemPosition()).pays.add(p);save();payments();});for(Client cl:clients)for(Pay p:cl.pays){Button b=btn((p.paid?"Pagado: ":"Pendiente: ")+cl.name+" $"+p.amount+" " +p.date+" (tocar para revertir)");b.setOnClickListener(v->{p.paid=!p.paid;save();payments();});content.addView(b);}}
 ArrayList<String> names(){ArrayList<String>n=new ArrayList<>();for(Client c:clients)n.add(c.name);return n;}
 void dash(){double paid=0,pend=0;content.addView(tv("Dashboard de ingresos",24,1));for(Client c:clients){double cp=0,cd=0;for(Pay p:c.pays){if(p.paid){paid+=p.amount;cp+=p.amount;}else{pend+=p.amount;cd+=p.amount;}}content.addView(tv(c.name+": recibido $"+cp+" / pendiente $"+cd,16,0));}content.addView(tv("Total del mes: $"+paid,22,1));content.addView(tv("Recibido: $"+paid+"   Pendiente: $"+pend,18,1));}
 void pending(){content.addView(tv("Pagos pendientes",24,1));for(Client c:clients)for(Pay p:c.pays)if(!p.paid)content.addView(tv(c.name+" debe $"+p.amount+" - vence "+p.date,17,1));}
 void alerts(){content.addView(tv("Notificaciones",24,1));long now=System.currentTimeMillis();for(Client c:clients)for(Pay p:c.pays)if(!p.paid)try{long days=(fmt.parse(p.date).getTime()-now)/86400000; if(days<0)content.addView(tv("VENCIDO: "+c.name+" desde "+p.date,17,1)); else if(days<=3)content.addView(tv("Próximo a vencer: "+c.name+" en "+days+" días",17,1));}catch(Exception e){}}
 void save(){try{JSONArray arr=new JSONArray();for(Client c:clients){JSONObject o=new JSONObject();o.put("n",c.name);o.put("t",c.phone);o.put("ph",c.photo);JSONArray ps=new JSONArray();for(Pay p:c.pays){JSONObject po=new JSONObject();po.put("d",p.date);po.put("a",p.amount);po.put("p",p.paid);ps.put(po);}o.put("ps",ps);arr.put(o);}sp.edit().putString("data",arr.toString()).apply();}catch(Exception e){}}
 void load(){try{JSONArray arr=new JSONArray(sp.getString("data","[]"));for(int i=0;i<arr.length();i++){JSONObject o=arr.getJSONObject(i);Client c=new Client();c.name=o.optString("n");c.phone=o.optString("t");c.photo=o.optString("ph");JSONArray ps=o.optJSONArray("ps");if(ps!=null)for(int j=0;j<ps.length();j++){JSONObject po=ps.getJSONObject(j);Pay p=new Pay();p.date=po.optString("d");p.amount=po.optDouble("a");p.paid=po.optBoolean("p");c.pays.add(p);}clients.add(c);}}catch(Exception e){}}
}
